### ISSUE TITLE
Non-English characters garbled in message body and text attachments

### ISSUE THREAD

**Issue by Kuitsi** [ChangemakerStudios/Papercut#12]
For example ISO-8859-1 characters å, ä and ö (codepoints 229, 228, 246) gets all interpreted in UTF-8 and thus are getting replaced with Unicode Replacement Character (\uFFFD), seen as ï¿½ in Message tab in Papercut.

Both the message body and attachment contents were "åäö" (and message includes information which charset should be used) when the message was sent and it works with real SMTP server. Attached the .eml file from Papercut's folder (Github required the additional .txt extension) [20160210-144849-74ba54.eml.txt](https://github.com/Jaben/Papercut/files/124710/20160210-144849-74ba54.eml.txt) shows that faulty encoding occurs before Papercut saves the .eml file.

**Comment by Jaben** [comment]
Please check latest -- I believe this issue has been fixed.

**Comment by Kuitsi** [comment]
Oh, there are newer releases available here on GitHub. I'll check this soon. I had that old 4.5.0 from CodePlex and that site seems to be shutting down now. Time to remove those CodePlex links from readme etc?

**Comment by vasiluy-kondr** [comment]
The issue is still occurs on v5.1.3 both with service enabled and without it.

![Papercut Main Window](https://i.imgur.com/jKt8sHo.png)

![Wireshark Conversation Dump](https://i.imgur.com/rHLvZ4n.png)
